
// GenesysCloud version number: v2.3.1
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef GENESYSCLOUD_SWIFT_H
#define GENESYSCLOUD_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="GenesysCloud",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class Account;
SWIFT_CLASS("_TtC12GenesysCloud20AuthenticationStatus")
@interface AuthenticationStatus : NSObject
+ (void)shouldAuthorizeWithAccount:(Account * _Nonnull)account completion:(void (^ _Nonnull)(BOOL))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12GenesysCloud23ChatAvailabilityChecker")
@interface ChatAvailabilityChecker : NSObject
+ (void)checkAvailability:(Account * _Nonnull)account completion:(void (^ _Nonnull)(BOOL))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ChatElementDelegate;
@protocol ChatControllerDelegate;
@class NSString;
/// The primary entry point for integrating the Genesys Cloud chat experience into a host application.
/// <code>ChatController</code> manages the lifecycle of a chat session, including starting, ending, reconnecting,
/// and presenting the chat UI. The host application creates an instance with a configured <code>MessengerAccount</code>
/// and assigns a <code>ChatControllerDelegate</code> to receive lifecycle callbacks.
/// <h2>Prerequisites</h2>
/// <ul>
///   <li>
///     A valid <code>MessengerAccount</code> configured with a deployment ID and domain.
///   </li>
///   <li>
///     The <code>delegate</code> property must be set to trigger chat initialization.
///   </li>
/// </ul>
/// <h2>Usage</h2>
/// \code
/// let account = MessengerAccount(
///     deploymentId: "your-deployment-id",
///     domain: "your-domain.com",
///     logging: true,
///     sessionExpirationNoticeInterval: 300
/// )
/// let chatController = ChatController(account: account)
/// chatController.delegate = self
///
/// \endcodeimportant:
/// Setting the <code>delegate</code> property initiates the chat session. Ensure the account
/// is fully configured before assigning the delegate.
SWIFT_CLASS("_TtC12GenesysCloud14ChatController")
@interface ChatController : NSObject
/// The delegate that receives chat element events as they arrive during a conversation.
/// Assign this delegate to receive individual <code>ChatElement</code> instances (messages, files, system events)
/// as they are delivered by the chat engine. This enables the host application to build custom chat
/// history or analytics on top of the SDK.
/// important:
/// Set this property before assigning <code>delegate</code> to ensure no elements are missed
/// during chat initialization.
@property (nonatomic, weak) id <ChatElementDelegate> _Nullable chatElementDelegate;
/// The delegate that receives chat lifecycle and presentation callbacks.
/// Setting this property triggers the chat session to start. The delegate will receive a call to
/// <code>ChatControllerDelegate/shouldPresentChatViewController(_:)</code> once the chat UI is ready
/// for presentation.
/// important:
/// Setting this to a non-nil value initiates the chat connection. Setting it to <code>nil</code>
/// does not end the chat; use <code>endChat(_:)</code> or <code>terminate()</code> for that purpose.
@property (nonatomic, weak) id <ChatControllerDelegate> _Nullable delegate;
/// Creates a new chat controller with the specified account configuration.
/// important:
/// This initializer does not start the chat session. Assign the <code>delegate</code> property
/// to initiate the connection and present the chat UI.
/// \param account A configured <code>MessengerAccount</code> instance containing the deployment ID,
/// domain, and other session parameters. The account must be fully configured before passing it here.
///
- (nonnull instancetype)initWithAccount:(Account * _Nonnull)account OBJC_DESIGNATED_INITIALIZER;
/// Ends the current chat session.
/// note:
/// After calling this method, the delegate will receive a <code>ChatControllerDelegate/didUpdateState(_:)</code>
/// callback with the <code>.chatEnding</code> and subsequently <code>.chatEnded</code> states.
/// \param forceClose When <code>true</code>, the chat is terminated immediately without waiting for
/// a graceful server-side disconnect. When <code>false</code>, the SDK performs a graceful shutdown,
/// attempting delivery of pending messages before disconnecting websocket.
///
- (void)endChat:(BOOL)forceClose;
/// Attempts to reconnect a disconnected chat session.
/// Call this method after receiving a <code>.chatDisconnected</code> state event to re-establish the
/// WebSocket connection and resume the conversation. The delegate will receive
/// <code>.chatReconnecting</code> followed by <code>.chatReconnected</code> on success, or <code>.chatDisconnected</code>
/// again on failure.
- (void)reconnectChat;
/// Clears the current conversation history from the session.
/// This removes all messages from the active conversation. The chat session remains active
/// and new messages can continue to be sent and received.
/// note:
/// This operation may fail in which case an error via <code>ChatControllerDelegate/didFailWithError(_:)</code> delegate method
/// will be returned:
/// <ul>
///   <li>
///     <code>.clearConversationDisabled</code>: Clear conversation feature is disabled in the deployment configuration.
///   </li>
///   <li>
///     <code>.clearConversationFailure</code>: Feature is enabled, but clearing the conversation failed.
///   </li>
/// </ul>
- (void)clearConversation;
/// Logs out from the current authenticated session.
/// Call this method to end an authenticated user’s session and clear stored authentication tokens.
/// After logout, a new authentication flow must be completed before starting another chat session.
/// important:
/// This method should only be called when the chat was started with authentication
/// (via <code>MessengerAccount/setAuthenticationInfo(authCode:redirectUri:codeVerifier:)</code> or
/// <code>MessengerAccount/setImplicitAuthenticationInfo(idToken:nonce:)</code>).
- (void)logoutFromAuthenticatedSession;
/// Terminates the chat controller and releases all associated resources.
/// This method performs a complete teardown of the chat controller, including ending any active
/// chat session, removing all delegate references, and releasing the chat UI. After calling this
/// method, the <code>ChatController</code> instance cannot be reused.
/// important:
/// Always call this method when the chat controller is no longer needed (e.g., when
/// the hosting view controller is deallocated) to prevent memory leaks and ensure pending
/// callbacks are safely discarded.
- (void)terminate;
/// Updates the custom attributes associated with the current chat session.
/// Custom attributes are key-value pairs that are sent to the server and can be used for routing,
/// reporting, or agent-side context. Attributes are merged with any previously set values.
/// \param customAttributes A dictionary of string key-value pairs to attach to the session.
///
- (void)updateCustomAttributes:(NSDictionary<NSString *, NSString *> * _Nonnull)customAttributes;
/// Checks whether the chat deployment is currently available for new conversations.
/// Use this method to verify availability before presenting chat UI to the user. Availability
/// depends on the deployment’s schedule, agent availability, and configuration.
/// \param account A configured <code>MessengerAccount</code> instance to check availability for.
///
/// \param completion A closure called on completion with <code>true</code> if chat is available,
/// or <code>false</code> if the deployment is currently unavailable.
///
+ (void)checkAvailability:(Account * _Nonnull)account completion:(void (^ _Nonnull)(BOOL))completion;
/// Reauthorizes the implicit authentication flow with a new token after expiration.
/// Call this method when you receive an <code>authorizationRequired</code> error via
/// <code>ChatControllerDelegate/didFailWithError(_:)</code> during an active authenticated session.
/// This refreshes the authentication without requiring a full session restart.
/// important:
/// This method should only be called while there is an active session that was
/// originally started with implicit authentication.
/// \param idToken A fresh OpenID Connect ID token obtained from your identity provider.
///
/// \param nonce The nonce value used when requesting the new token, for replay protection.
///
- (void)reauthorizeImplicitFlowWithIdToken:(NSString * _Nonnull)idToken nonce:(NSString * _Nonnull)nonce;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UINavigationController;
@class ChatStateEvent;
@class GCError;
/// A protocol that the host application implements to receive chat lifecycle events and presentation requests.
/// Conforming to this protocol allows the host application to control how the chat UI is presented,
/// respond to chat state changes, handle link taps, and receive error notifications.
/// <h2>Usage</h2>
/// Assign a conforming object to <code>ChatController/delegate</code> to begin receiving callbacks.
/// The <code>shouldPresentChatViewController(_:)</code> method is required and will be called once the
/// chat session is ready for display.
/// \code
/// class MyViewController: UIViewController, ChatControllerDelegate {
///     func shouldPresentChatViewController(_ viewController: UINavigationController!) {
///         viewController.modalPresentationStyle = .overFullScreen
///         present(viewController, animated: true)
///     }
/// }
///
/// \endcode
SWIFT_PROTOCOL("_TtP12GenesysCloud22ChatControllerDelegate_")
@protocol ChatControllerDelegate <NSObject>
/// Notifies the delegate to present the chat interface.
/// This delegate is triggered when the chat is configured and has established a connection. This method provides a <code>UINavigationController</code> that encapsulates the chat UI, allowing the host application to present it.
/// <h2>Usage</h2>
/// Implement this method in the class conforming to the delegate to control how the chat interface
/// is presented. Typically, the application displays the view controller modally or pushes it onto
/// an existing navigation stack.
/// <h3>Swift</h3>
/// \code
/// func shouldPresentChatViewController(_ viewController: UINavigationController!) {
///     viewController.modalPresentationStyle = .overFullScreen
///     present(viewController, animated: true)
/// }
///
/// \endcodeimportant:
/// For proper initialization of the full chat life cycle the navigation controller must be immediately presented.
/// \param viewController A <code>UINavigationController</code> instance that contains the chat view
/// controller. The host application can display this view controller using standard
/// presentation methods (e.g., modal presentation or pushing it onto a navigation stack).
///
- (void)shouldPresentChatViewController:(UINavigationController * _Null_unspecified)viewController;
@optional
/// The <code>didClickLink</code> delegate is triggered when the user interacts with a tappable link in chat messages. The host application can provide custom implementation. If the delegate is not implemented by the host application, links retain their default tap behavior, otherwise the host application is responsible for handling links.
/// \param url A <code>String</code> containing the URL that was tapped.
///
- (void)didClickLink:(NSString * _Nonnull)url;
/// Notifies the delegate of a change in the chat’s state.
/// This delegate is triggered when there is a change in the chat state. The host application can monitor and respond to state changes, such as when a chat starts, disconnects, or ends.
/// <h2>Chat States</h2>
/// The chat can be in one of the following states, represented by the <code>ChatState</code> enum (raw values in parentheses):
/// <ul>
///   <li>
///     <code>chatCreated (1)</code>: The chat session has been created but not started.
///   </li>
///   <li>
///     <code>chatStarted (2)</code>: The chat session has started.
///   </li>
///   <li>
///     <code>chatPreparing (3)</code>: The chat is preparing socket connection.
///   </li>
///   <li>
///     <code>chatPrepared (4)</code>: The chat has been prepared, configuration fetched and is ready.
///   </li>
///   <li>
///     <code>chatDisconnected (5)</code>: The chat has been disconnected in case of an error.
///   </li>
///   <li>
///     <code>chatReconnecting (6)</code>: The chat is attempting to reconnect.
///   </li>
///   <li>
///     <code>chatReconnected (7)</code>: The chat has successfully reconnected.
///   </li>
///   <li>
///     <code>chatEnding (8)</code>: The chat is in the process of ending.
///   </li>
///   <li>
///     <code>chatEnded (9)</code>: The chat session has ended.
///   </li>
///   <li>
///     <code>chatClosed (10)</code>: The chat has closed.
///   </li>
///   <li>
///     <code>unavailable (18)</code>: The chat is unavailable.
///   </li>
/// </ul>
/// <h2>Usage</h2>
/// Implement this method in the delegate to respond to changes in the chat’s lifecycle.
/// Common use cases include updating the UI, logging chat state transitions, or performing
/// actions based on specific states.
/// <h3>Swift</h3>
/// \code
/// func didUpdateState(_ event: ChatStateEvent) {
///     switch event.state {
///     case .chatStarted:
///         // handle chat started
///     case .chatEnded:
///         // handle chat ended
///     default:
///         // handle other states
///     }
/// }
///
/// \endcode\param event A <code>ChatStateEvent</code> instance representing the current state of the chat.
/// The <code>ChatState</code> enumeration defines the possible states of the chat lifecycle.
///
- (void)didUpdateState:(ChatStateEvent * _Nonnull)event;
/// Notifies the delegate that an error occurred during the chat session.
/// This method is called when the SDK encounters an error that the host application should be
/// aware of, and in some cases must handle in order to ensure proper chat functionality.
/// <h2>Usage</h2>
/// \code
/// func didFailWithError(_ error: GCError?) {
///     guard let error = error else { return }
///     showAlert(message: error.errorDescription ?? "An error occurred")
/// }
///
/// \endcode\param error A <code>GCError</code> instance describing the failure, or <code>nil</code> if the error
/// details are unavailable. Inspect the error’s <code>errorType</code> and <code>errorDescription</code> properties
/// for specifics.
///
- (void)didFailWithError:(GCError * _Nullable)error;
@end

@class ChatElement;
/// A protocol for receiving individual chat elements as they arrive during a conversation.
/// Implement this protocol to receive real-time notifications when new chat elements (messages,
/// files, system events, typing indicators) are delivered by the chat engine. This is useful for
/// building custom chat history, analytics, or notification features on top of the SDK.
/// <h2>Usage</h2>
/// Assign a conforming object to <code>ChatController/chatElementDelegate</code> before setting the
/// <code>ChatController/delegate</code> to ensure no elements are missed during initialization.
/// \code
/// class ChatHistoryTracker: NSObject, ChatElementDelegate {
///     func didReceive(chatElement: ChatElement) {
///         // Process or store the received element
///     }
/// }
///
/// \endcode@mockable
SWIFT_PROTOCOL("_TtP12GenesysCloud19ChatElementDelegate_")
@protocol ChatElementDelegate
/// Called when a new chat element is received from the chat engine.
/// This method is invoked for every element delivered during the conversation, including
/// messages loaded from history when reconnecting to an existing session.
/// Websocket connection can close when the application enters background, preventing elements to be received until reconnection.
/// \param chatElement The received <code>ChatElement</code> instance. Inspect its concrete type
/// (e.g., <code>TextChatElement</code>, <code>FileChatElement</code>, <code>SystemChatElement</code>) for type-specific data.
///
- (void)didReceiveWithChatElement:(ChatElement * _Nonnull)chatElement;
@end

enum PushProvider : NSInteger;
/// Manages push notification registration and deregistration for the SDK.
/// Use this class to register or remove device push tokens so that the user receives
/// notifications for incoming chat messages when the app is in the background.
/// <h2>Prerequisites</h2>
/// <ul>
///   <li>
///     A configured <code>MessengerAccount</code> with a valid deployment ID and domain.
///   </li>
///   <li>
///     A device token obtained from APNs or FCM.
///   </li>
///   <li>
///     Push notification integration is properly configured in deployment settings.
///   </li>
/// </ul>
/// <h2>Usage</h2>
/// \code
/// // Register for push notifications
/// ChatPushNotificationIntegration.setPushToken(
///     deviceToken: tokenString,
///     pushProvider: .apns,
///     account: messengerAccount
/// ) { result in
///     switch result {
///     case .success:
///         // Push token registered
///     case .failure(let error):
///         // Registration failed with error
///     }
/// }
///
/// \endcodeimportant:
/// Push token registration should be performed each time the app receives a new
/// device token (e.g., in <code>application(_:didRegisterForRemoteNotificationsWithDeviceToken:)</code>).
SWIFT_CLASS("_TtC12GenesysCloud31ChatPushNotificationIntegration")
@interface ChatPushNotificationIntegration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Registers a device push token (Objective-C compatible variant).
/// This method provides the same functionality as
/// <code>setPushToken(deviceToken:pushProvider:account:completion:)-swift.type.method</code>
/// with an Objective-C compatible completion handler.
/// \param deviceToken The device token string obtained from the push notification provider.
///
/// \param pushProvider The push notification provider (<code>.apns</code> or <code>.fcm</code>).
///
/// \param account A configured <code>MessengerAccount</code> instance.
///
/// \param completion A closure called with <code>nil</code> on success, or a <code>GCError</code> on failure.
///
+ (void)setPushTokenForObjectiveCWithDeviceToken:(NSString * _Nonnull)deviceToken pushProvider:(enum PushProvider)pushProvider account:(Account * _Nonnull)account completion:(void (^ _Nonnull)(GCError * _Nullable))completion;
/// Removes the previously registered push token (Objective-C compatible variant).
/// This method provides the same functionality as
/// <code>removePushToken(account:completion:)-swift.type.method</code>
/// with an Objective-C compatible completion handler.
/// \param account The <code>MessengerAccount</code> instance that was used to register the token.
///
/// \param completion A closure called with <code>nil</code> on success, or a <code>GCError</code> on failure.
///
+ (void)removePushTokenWithAccount:(Account * _Nonnull)account completion:(void (^ _Nonnull)(GCError * _Nullable))completion;
@end

@class UIColor;
@class UIFont;
@class NSTextContainer;
@class NSCoder;
@class UITraitCollection;
IB_DESIGNABLE
SWIFT_CLASS("_TtC12GenesysCloud15GrowingTextView") SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.")
@interface GrowingTextView : UITextView
@property (nonatomic, copy) NSString * _Null_unspecified text;
@property (nonatomic) IBInspectable NSInteger maxLength;
@property (nonatomic) IBInspectable BOOL trimWhiteSpaceWhenEndEditing;
@property (nonatomic) IBInspectable CGFloat minHeight;
@property (nonatomic) IBInspectable CGFloat maxHeight;
@property (nonatomic, copy) IBInspectable NSString * _Nullable placeholder;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull placeholderColor;
@property (nonatomic, strong) IBInspectable UIFont * _Nonnull placeholderFont;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previous;
- (void)layoutSubviews;
- (void)drawRect:(CGRect)rect;
@end

typedef SWIFT_ENUM(NSInteger, PresentationState, open) {
  PresentationStateNone = 0,
  PresentationStateTypingPlaceholder = 1,
  PresentationStateTypingSendDisabled = 2,
  PresentationStateTypingSendEnabled = 3,
  PresentationStateAttachmentNoText = 4,
};

/// The push notification provider used for delivering chat notifications.
/// Specify the provider that matches your application’s push notification integration
/// when registering a device token with <code>ChatPushNotificationIntegration</code>.
typedef SWIFT_ENUM(NSInteger, PushProvider, open) {
/// Apple Push Notification service (APNs).
  PushProviderApns = 0,
/// Firebase Cloud Messaging (FCM).
  PushProviderFcm = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
