
// GenesysCloud version number: v1.17.0
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef GENESYSCLOUD_SWIFT_H
#define GENESYSCLOUD_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import GenesysCloudCore;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="GenesysCloud",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class Account;

SWIFT_CLASS("_TtC12GenesysCloud20AuthenticationStatus")
@interface AuthenticationStatus : NSObject
+ (void)shouldAuthorizeWithAccount:(Account * _Nonnull)account completion:(void (^ _Nonnull)(BOOL))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC12GenesysCloud18AvailabilityResult")
@interface AvailabilityResult : NSObject
@property (nonatomic, readonly) BOOL isAvailable;
@property (nonatomic, readonly) enum UnavailableReason reason;
@property (nonatomic, readonly) NSError * _Nullable error;
@property (nonatomic, readonly, copy) NSString * _Nullable departmentId SWIFT_DEPRECATED_MSG("Not used, will be removed");
@property (nonatomic, readonly, copy) NSString * _Nullable apiKey SWIFT_DEPRECATED_MSG("Not used, will be removed");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class RemoteConfiguration;

SWIFT_CLASS("_TtC12GenesysCloud23ChatAvailabilityChecker")
@interface ChatAvailabilityChecker : NSObject <ConfigurationLoaderDelegate>
+ (void)checkAvailability:(Account * _Nonnull)account completion:(void (^ _Nonnull)(AvailabilityResult * _Nullable))completion;
- (void)didFailLoadWithError:(NSError * _Nullable)error;
- (void)didFetchChatSettingsWithRemoteConfig:(RemoteConfiguration * _Nonnull)remoteConfig;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ChatElementDelegate;
@protocol ChatControllerDelegate;
@class MessengerChatEngine;

SWIFT_CLASS("_TtC12GenesysCloud14ChatController")
@interface ChatController : NSObject
/// The History Provider for Controlling Chat History.
@property (nonatomic, weak) id <ChatElementDelegate> _Nullable chatElementDelegate;
/// Chat Controller Delegate
@property (nonatomic, weak) id <ChatControllerDelegate> _Nullable delegate;
- (nonnull instancetype)initWithAccount:(Account * _Nonnull)account engine:(MessengerChatEngine * _Nullable)engine OBJC_DESIGNATED_INITIALIZER;
/// Ends current chat handler.
- (void)endChat:(BOOL)forceClose;
/// Reconnect current chat handler.
- (void)reconnectChat;
/// Clear current conversation.
- (void)clearConversation;
/// Logout current chat handler.
- (void)logoutFromAuthenticatedSession;
/// Terminates the chat controller and all active chats.
- (void)terminate;
/// Updating custom attributes.
- (void)updateCustomAttributes:(NSDictionary<NSString *, NSString *> * _Nonnull)customAttributes;
/// The availability of the chat.
+ (void)checkAvailability:(Account * _Nonnull)account completion:(void (^ _Nonnull)(AvailabilityResult * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@class UINavigationController;
@class ChatStateEvent;
@class GCError;
@protocol StorableChatElement;
@class NSError;
@class UIViewController;

SWIFT_PROTOCOL("_TtP12GenesysCloud22ChatControllerDelegate_")
@protocol ChatControllerDelegate <NSObject>
/// Notifies the delegate to present the chat interface.
/// This delegate is triggered when the chat is configured and has established a connection. This method provides a <code>UINavigationController</code> that encapsulates the chat UI, allowing the host application to present it as needed.
/// <h2>Usage</h2>
/// Implement this method in the class conforming to the delegate to control how the chat interface
/// is presented. Typically, the application displays the view controller modally or pushes it onto
/// an existing navigation stack.
/// <h3>Swift</h3>
/// \code
/// func shouldPresentChatViewController(_ viewController: UINavigationController!) {
///     viewController.modalPresentationStyle = .overFullScreen
///     self.present(viewController, animated: true)
/// }
///
/// \endcode\param viewController A <code>UINavigationController</code> instance that contains the chat view
/// controller. The host application can display this view controller using standard
/// presentation methods (e.g., modal presentation or pushing it onto a navigation stack).
///
- (void)shouldPresentChatViewController:(UINavigationController * _Null_unspecified)viewController;
@optional
/// The <code>didClickLink</code> delegate is triggered when the user interacts with a tappable link in chat messages. The host application can provide custom implementation. If the delegate is not implemented by the host application, links retain their default tap behavior, otherwise the host application is responsible for handling links.
/// \param url A <code>String</code> containing the URL that was tapped.
///
- (void)didClickLink:(NSString * _Nonnull)url;
/// Notifies the delegate of a change in the chat’s state.
/// This delegate is triggered when there is a change in the chat state. The host application can monitor and respond to state changes, such as when a chat starts, disconnects, or ends.
/// <h2>Chat States</h2>
/// The chat can be in one of the following states, represented by the <code>ChatState</code> enum (raw values in parentheses):
/// <ul>
///   <li>
///     <code>chatCreated (1)</code>: The chat session has been created but not started.
///   </li>
///   <li>
///     <code>chatStarted (2)</code>: The chat session has started.
///   </li>
///   <li>
///     <code>chatPreparing (3)</code>: The chat is preparing socket connection.
///   </li>
///   <li>
///     <code>chatPrepared (4)</code>: The chat has been prepared, configuration fetched and is ready.
///   </li>
///   <li>
///     <code>chatDisconnected (5)</code>: The chat has been disconnected in case of an error.
///   </li>
///   <li>
///     <code>chatReconnecting (6)</code>: The chat is attempting to reconnect.
///   </li>
///   <li>
///     <code>chatReconnected (7)</code>: The chat has successfully reconnected.
///   </li>
///   <li>
///     <code>chatEnding (8)</code>: The chat is in the process of ending.
///   </li>
///   <li>
///     <code>chatEnded (9)</code>: The chat session has ended.
///   </li>
///   <li>
///     <code>chatClosed (10)</code>: The chat has closed.
///   </li>
///   <li>
///     <code>unavailable (18)</code>: The chat is unavailable.
///   </li>
/// </ul>
/// <h2>Usage</h2>
/// Implement this method in the delegate to respond to changes in the chat’s lifecycle.
/// Common use cases include updating the UI, logging chat state transitions, or performing
/// actions based on specific states.
/// <h3>Swift</h3>
/// \code
/// func didUpdateState(_ event: ChatStateEvent) {
///     switch event.state {
///     case .chatStarted:
///         // handle chat started
///     case .chatEnded:
///         // handle chat ended
///     default:
///         // handle other states
///     }
/// }
///
/// \endcode\param event A <code>ChatStateEvent</code> instance representing the current state of the chat.
/// The <code>ChatState</code> enumeration defines the possible states of the chat lifecycle.
///
- (void)didUpdateState:(ChatStateEvent * _Nonnull)event;
/// The <code>didFailWithError</code> delegate is triggered in case of errors. The <code>GCError</code> parameter contains details about the error.
- (void)didFailWithError:(GCError * _Nullable)error;
- (void)statement:(id <StorableChatElement> _Nonnull)statement didFailWithError:(NSError * _Nonnull)error SWIFT_DEPRECATED_MSG("Function not utilized, will be removed. Use ChatElementDelegate instead.");
- (void)didClickUploadFile SWIFT_DEPRECATED_MSG("Function not utilized, will be removed.");
- (void)presentingController:(UIViewController * _Nonnull)controller shouldHandleClickedLink:(NSString * _Nonnull)link SWIFT_DEPRECATED_MSG("Function not utilized, will be removed.");
- (void)updateCustomAttributes:(NSDictionary<NSString *, NSString *> * _Nonnull)customAttributes SWIFT_DEPRECATED_MSG("Function not utilized, will be removed.");
- (void)didClickToCall:(NSString * _Nonnull)phoneNumber SWIFT_DEPRECATED_MSG("Function not utilized, will be removed.");
- (BOOL)shouldPresentWelcomeMessage SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Function not utilized, will be removed.");
- (BOOL)shouldHandleFormPresentation:(UIViewController * _Nonnull)formController SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Function not utilized, will be removed.");
- (void)reconnectChat SWIFT_DEPRECATED_MSG("Function not utilized, will be removed.");
- (void)didLogoutChat SWIFT_DEPRECATED_MSG("Function not utilized, will be removed.");
@end


@class ChatElement;
enum StatementStatus : NSInteger;

SWIFT_PROTOCOL("_TtP12GenesysCloud19ChatElementDelegate_")
@protocol ChatElementDelegate
- (void)didReceiveWithChatElement:(ChatElement * _Nonnull)chatElement;
- (void)didReceiveChatElement:(id <StorableChatElement> _Nonnull)item SWIFT_DEPRECATED_MSG("StoreableChatElement is replaced by ChatElement");
@optional
- (void)fetch:(NSInteger)from handler:(SWIFT_NOESCAPE NSArray<id <StorableChatElement>> * _Nonnull (^ _Nonnull)(void))handler SWIFT_DEPRECATED_MSG("Not utilized, will be removed.");
- (void)didRemoveChatElement:(NSTimeInterval)timestampId SWIFT_DEPRECATED_MSG("Not utilized, will be removed.");
- (void)didUpdateChatElement:(NSTimeInterval)timestampId newTimestamp:(NSTimeInterval)newTimestamp status:(enum StatementStatus)status SWIFT_DEPRECATED_MSG("Will be removed.");
@end

typedef SWIFT_ENUM(NSInteger, ChatElementType, open) {
  ChatElementTypeOutgoingElement = 0,
  ChatElementTypeIncomingBotElement = 1,
  ChatElementTypeIncomingLiveElement = 2,
  ChatElementTypeCarouselElement = 3,
  ChatElementTypeSystemMessageElement = 4,
  ChatElementTypeIncomingBotMultipleSelectionElement = 5,
};

enum PushProvider : NSInteger;

SWIFT_CLASS("_TtC12GenesysCloud31ChatPushNotificationIntegration")
@interface ChatPushNotificationIntegration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)setPushTokenForObjectiveCWithDeviceToken:(NSString * _Nonnull)deviceToken pushProvider:(enum PushProvider)pushProvider account:(Account * _Nonnull)account completion:(void (^ _Nonnull)(GCError * _Nullable))completion;
+ (void)removePushTokenWithAccount:(Account * _Nonnull)account completion:(void (^ _Nonnull)(GCError * _Nullable))completion;
@end

@class NSDate;

SWIFT_PROTOCOL("_TtP12GenesysCloud19StorableChatElement_") SWIFT_DEPRECATED_MSG("Replaced by new ChatElelement structure")
@protocol StorableChatElement
@property (nonatomic) enum StatementStatus status;
@property (nonatomic, copy) NSString * _Nonnull elementId;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSDate * _Nonnull timestamp;
@property (nonatomic) enum ChatElementType type;
@end


SWIFT_CLASS("_TtC12GenesysCloud18ContentChatElement") SWIFT_DEPRECATED_MSG("Replaced by new ChatElelement structure")
@interface ContentChatElement : NSObject <StorableChatElement>
@property (nonatomic) enum StatementStatus status;
@property (nonatomic, copy) NSString * _Nonnull elementId;
@property (nonatomic) enum ChatElementType type;
@property (nonatomic, copy) NSDate * _Nonnull timestamp;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic) BOOL isPreceding;
- (nonnull instancetype)initWithType:(enum ChatElementType)type content:(NSString * _Nonnull)content OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum ChatElementType)type content:(NSString * _Nonnull)content elementId:(NSString * _Nonnull)elementId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@class UIColor;
@class UIFont;
@class NSTextContainer;
@class NSCoder;
@class UITraitCollection;

IB_DESIGNABLE
SWIFT_CLASS("_TtC12GenesysCloud15GrowingTextView")
@interface GrowingTextView : UITextView
@property (nonatomic, copy) NSString * _Null_unspecified text;
@property (nonatomic) IBInspectable NSInteger maxLength;
@property (nonatomic) IBInspectable BOOL trimWhiteSpaceWhenEndEditing;
@property (nonatomic) IBInspectable CGFloat minHeight;
@property (nonatomic) IBInspectable CGFloat maxHeight;
@property (nonatomic, copy) IBInspectable NSString * _Nullable placeholder;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull placeholderColor;
@property (nonatomic, strong) IBInspectable UIFont * _Nonnull placeholderFont;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previous;
- (void)layoutSubviews;
- (void)drawRect:(CGRect)rect;
@end


SWIFT_CLASS("_TtC12GenesysCloud16LocalChatElement") SWIFT_DEPRECATED_MSG("Replaced by new ChatElelement structure")
@interface LocalChatElement : ContentChatElement
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull quickReplies;
- (nonnull instancetype)initWithContent:(NSString * _Nonnull)content OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum ChatElementType)type content:(NSString * _Nonnull)content quickReplies:(NSArray<NSString *> * _Nonnull)quickReplies OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum ChatElementType)type content:(NSString * _Nonnull)content SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithType:(enum ChatElementType)type content:(NSString * _Nonnull)content elementId:(NSString * _Nonnull)elementId SWIFT_UNAVAILABLE;
@end


typedef SWIFT_ENUM(NSInteger, PresentationState, open) {
  PresentationStateNone = 0,
  PresentationStateTypingPlaceholder = 1,
  PresentationStateTypingSendDisabled = 2,
  PresentationStateTypingSendEnabled = 3,
  PresentationStateAttachmentNoText = 4,
};

typedef SWIFT_ENUM(NSInteger, PushProvider, open) {
  PushProviderApns = 0,
  PushProviderFcm = 1,
};

enum RemoteMessageType : NSInteger;

SWIFT_CLASS("_TtC12GenesysCloud17RemoteChatElement") SWIFT_DEPRECATED_MSG("Replaced by new ChatElelement structure")
@interface RemoteChatElement : ContentChatElement
@property (nonatomic) enum RemoteMessageType remoteMessageType;
- (nonnull instancetype)initWithRemoteMessageType:(enum RemoteMessageType)remoteMessageType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithType:(enum ChatElementType)type content:(NSString * _Nonnull)content SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithType:(enum ChatElementType)type content:(NSString * _Nonnull)content elementId:(NSString * _Nonnull)elementId SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, RemoteMessageType, open) {
  RemoteMessageTypeTypDefault = 0,
  RemoteMessageTypeTypWelcomeMessag = 1,
  RemoteMessageTypeTypFAQ = 2,
  RemoteMessageTypeConversationDisconnect = 3,
};

typedef SWIFT_ENUM(NSInteger, StatementStatus, open) {
  StatementStatusOK = 0,
  StatementStatusPending = 1,
  StatementStatusError = 2,
  StatementStatusRepost = 3,
  StatementStatusNone = 4,
  StatementStatusInProcess = 5,
};












#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
