
// GenesysCloudCore version number: v2.3.1
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef GENESYSCLOUDCORE_SWIFT_H
#define GENESYSCLOUDCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="GenesysCloudCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC16GenesysCloudCore7Account") SWIFT_DEPRECATED_MSG("Should not be subclassed by external users. Will be changed from open to public in 3.0.0.")
@interface Account : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC16GenesysCloudCore17AttachmentProfile") SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.")
@interface AttachmentProfile : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class CardAction;
@class UIImage;
/// A single card within a <code>CarouselChatElement</code>.
/// Each card represents one item in the carousel and can display a title, description,
/// optional image, and a list of interactive actions (buttons/links).
SWIFT_CLASS("_TtC16GenesysCloudCore4Card")
@interface Card : NSObject
/// The title text displayed prominently on the card.
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
/// A longer description displayed below the title.
@property (nonatomic, readonly, copy) NSString * _Nonnull cardDescription;
/// The URL of the card’s header image, or <code>nil</code> if no image is provided.
@property (nonatomic, readonly, copy) NSString * _Nullable imageUrl;
/// The interactive actions (buttons) displayed at the bottom of the card.
@property (nonatomic, readonly, copy) NSArray<CardAction *> * _Nonnull actions;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title cardDescription:(NSString * _Nonnull)cardDescription imageUrl:(NSString * _Nullable)imageUrl image:(UIImage * _Nullable)image actions:(NSArray<CardAction *> * _Nonnull)actions OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
/// An interactive action button on a <code>Card</code> within a carousel.
/// Card actions represent tappable buttons that can either open a URL or send a postback
/// payload to the bot. The <code>text</code> property provides the button label, while <code>url</code> and
/// <code>payload</code> determine the action’s behavior.
SWIFT_CLASS("_TtC16GenesysCloudCore10CardAction")
@interface CardAction : NSObject
/// The display text for the action button.
@property (nonatomic, readonly, copy) NSString * _Nonnull text;
/// The URL to open when the action is tapped, or <code>nil</code> for postback-only actions.
@property (nonatomic, readonly, copy) NSURL * _Nullable url;
/// The postback payload string sent to the bot when the action is tapped.
@property (nonatomic, readonly, copy) NSString * _Nonnull payload;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text url:(NSURL * _Nullable)url payload:(NSString * _Nonnull)payload OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;
enum ChatElementKind : NSInteger;
enum UserChatElementState : NSInteger;
/// The base class for all chat elements in a conversation.
/// A <code>ChatElement</code> represents a single item in the chat timeline — a message, file, system event,
/// carousel, quick reply, or typing indicator. The SDK delivers instances of concrete subclasses
/// through the <code>ChatElementDelegate</code> protocol.
/// <h2>Subclasses</h2>
/// note:
/// Do not subclass <code>ChatElement</code> in your application. This class will be changed from
/// <code>open</code> to <code>public</code> in a future release.
/// <ul>
///   <li>
///     <code>TextChatElement</code>: A plain text message from a user, agent, or bot.
///   </li>
///   <li>
///     <code>FileChatElement</code>: A file attachment (image, document, video, etc.).
///   </li>
///   <li>
///     <code>SystemChatElement</code>: A system-generated event (conversation started, ended, etc.).
///   </li>
///   <li>
///     <code>CarouselChatElement</code>: A horizontally scrollable set of rich cards.
///   </li>
///   <li>
///     <code>QuickRepliesChatElement</code>: A set of suggested reply buttons.
///   </li>
///   <li>
///     <code>TypingIndicatorChatElement</code>: Indicates the agent is currently typing.
///   </li>
///   <li>
///     <code>TimeSlotPickerChatElement</code>: A scheduling picker with available time slots.
///   </li>
///   <li>
///     <code>TimeSlotConfirmationChatElement</code>: Confirmation of a selected time slot.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC16GenesysCloudCore11ChatElement") SWIFT_DEPRECATED_MSG("Should not be subclassed by external users. Will be changed from open to public in 3.0.0.")
@interface ChatElement : NSObject
/// The unique identifier for this chat element.
@property (nonatomic, copy) NSString * _Nonnull id;
/// Indicates whether this element was loaded from conversation history rather than received in real time.
@property (nonatomic) BOOL isLoadedFromHistory;
/// The timestamp when this element was created or received.
@property (nonatomic, copy) NSDate * _Nonnull timestamp;
/// The origin of this element.
@property (nonatomic) enum ChatElementKind kind;
/// The current delivery state of this element when sent by the user.
/// This property is KVO-observable. Use it to drive UI updates for send-state indicators.
@property (nonatomic) enum UserChatElementState userState;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A chat element representing a horizontally scrollable carousel of rich cards.
/// Carousels are used to present multiple options (e.g., products, articles)
/// in a visually rich format. Each card can contain a title, description, image, and action buttons.
/// <h2>Accessing Carousel Content</h2>
/// \code
/// if let carousel = chatElement as? CarouselChatElement {
///     for card in carousel.cards {
///         // Handle card
///         for action in card.actions {
///             // Handle action
///         }
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC16GenesysCloudCore19CarouselChatElement")
@interface CarouselChatElement : ChatElement
/// The ordered list of cards displayed in the carousel.
@property (nonatomic, readonly, copy) NSArray<Card *> * _Nonnull cards;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp cards:(NSArray<Card *> * _Nonnull)cards OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC16GenesysCloudCore15ChatDataRequest") SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.")
@interface ChatDataRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Identifies the origin of a chat element within the conversation.
typedef SWIFT_ENUM(NSInteger, ChatElementKind, open) {
/// The element was sent by an agent or bot.
  ChatElementKindAgent = 0,
/// The element is a special system message (e.g. welcome message, quick replies).
  ChatElementKindSystem = 1,
/// The element was sent by the user.
  ChatElementKindUser = 2,
};

/// Error codes representing failures that can occur during a chat session.
/// These codes are delivered via <code>GCError/errorType</code> in the
/// <code>ChatControllerDelegate/didFailWithError(_:)</code> callback. Use the error type to determine
/// the appropriate recovery action in your application.
/// <h2>Handling Errors</h2>
/// \code
/// func didFailWithError(_ error: GCError?) {
///     guard let error = error else { return }
///     switch error.errorType {
///     case .failedToReconnect:
///         // Offer the user a reconnect option
///     case .authorizationRequired:
///         // Re-authenticate and call reauthorizeImplicitFlow
///     case .attachmentValidationError:
///         // Inform the user about file size/type restrictions
///     case .clientNotAuthenticatedError, .authLogoutFailed:
///         // Return to login screen
///     default:
///         // Show a generic error message
///     }
/// }
///
/// \endcode
typedef SWIFT_ENUM(NSInteger, ChatError, open) {
/// The chat session failed to load (e.g., configuration or connection failure during startup).
  ChatErrorFailedToLoad = 5001,
  ChatErrorFailedToEnd = 5002,
  ChatErrorAccountIsNotValid = 5003,
/// A general chat error that does not fit other categories.
  ChatErrorChatGeneralError = 5004,
/// Failed to load chat data (e.g., message history).
  ChatErrorFailedToLoadData = 5005,
  ChatErrorFailedToFetchAccountConfiguration = 5006,
/// A message failed to send.
  ChatErrorFailedToSendMessage = 5007,
  ChatErrorFailedToLoadHistory = 5008,
  ChatErrorFailedNoAccessKeyForLiveChat = 5009,
  ChatErrorFailedNoImplementationForHandOver = 5010,
/// The Messenger deployment is in a disabled state and cannot accept connections.
  ChatErrorFailedMessengerChatErrorDisableState = 5011,
  ChatErrorFailedToChangeLanguage = 5012,
/// A general error type used for miscellaneous failures.
  ChatErrorFailedGeneralErrorType = 5013,
  ChatErrorSessionExpiration = 5014,
  ChatErrorConnectionError = 5015,
/// An attempt to reconnect the chat session failed.
  ChatErrorFailedToReconnect = 5016,
/// The conversation could not be auto-started.
  ChatErrorFailedToAutostartConversation = 5017,
/// Custom attributes could not be sent to the server.
  ChatErrorFailedToSendCustomAttributes = 5018,
/// A new conversation could not be created.
  ChatErrorConversationCreationError = 5019,
/// An attachment failed to download.
  ChatErrorAttachmentDownloadError = 5020,
/// The client is not authenticated but attempted an operation requiring authentication.
  ChatErrorClientNotAuthenticatedError = 5021,
/// Logout from an authenticated session failed.
  ChatErrorAuthLogoutFailed = 5022,
/// An attachment failed validation (e.g., file too large or unsupported type).
  ChatErrorAttachmentValidationError = 5023,
/// An attachment failed to upload.
  ChatErrorAttachmentUploadError = 5024,
/// The clear conversation feature is disabled for this deployment.
  ChatErrorClearConversationDisabled = 5025,
/// The clear conversation operation failed.
  ChatErrorClearConversationFailure = 5026,
/// The push notification deployment ID does not match the account’s deployment.
  ChatErrorPushDeploymentIdMismatch = 5027,
/// The device is already registered for push notifications.
  ChatErrorDeviceAlreadyRegistered = 5028,
/// The authentication token has expired and reauthorization is required.
/// Handle by calling <code>ChatController/reauthorizeImplicitFlow(idToken:nonce:)</code>.
  ChatErrorAuthorizationRequired = 5029,
};

/// The lifecycle states of a chat session.
/// These states are delivered through <code>ChatStateEvent</code> via the
/// <code>ChatControllerDelegate/didUpdateState(_:)</code> delegate method. The typical happy-path
/// progression is:
/// <code>chatPreparing</code> → <code>chatPrepared</code> → <code>chatStarted</code> → <code>chatEnding</code> → <code>chatEnded</code> → <code>chatClosed</code>
/// <h2>Usage</h2>
/// \code
/// func didUpdateState(_ event: ChatStateEvent) {
///     switch event.state {
///     case .chatPreparing:
///         showLoadingIndicator()
///     case .chatStarted:
///         hideLoadingIndicator()
///     case .chatDisconnected:
///         showReconnectOption()
///     case .chatClosed:
///         if let reason = event.dataMsg as? Int,
///            let endedReason = EndedReason(rawValue: reason) {
///             handleChatClosed(reason: endedReason)
///         }
///     default:
///         break
///     }
/// }
///
/// \endcode
typedef SWIFT_ENUM(NSInteger, ChatState, open) {
/// The state has not been determined yet.
  ChatStateUnknown = 0,
/// The chat session object has been created but the connection has not started.
  ChatStateChatCreated = 1,
/// The chat session is active and messages can be exchanged.
  ChatStateChatStarted = 2,
/// The SDK is establishing the WebSocket connection and fetching configuration.
  ChatStateChatPreparing = 3,
/// Configuration has been fetched and the chat is ready to be presented.
  ChatStateChatPrepared = 4,
/// The WebSocket connection was lost unexpectedly.
  ChatStateChatDisconnected = 5,
/// The SDK is attempting to re-establish the connection.
  ChatStateChatReconnecting = 6,
/// The connection has been successfully re-established after a disconnect.
  ChatStateChatReconnected = 7,
/// The chat session is in the process of ending (graceful shutdown initiated).
  ChatStateChatEnding = 8,
/// The chat session has ended. The <code>ChatStateEvent/dataMsg</code> contains the <code>EndedReason</code> raw value.
  ChatStateChatEnded = 9,
/// The chat has fully closed and resources have been released.
/// The <code>ChatStateEvent/dataMsg</code> contains the <code>EndedReason</code> raw value.
  ChatStateChatClosed = 10,
/// Internal state for configuration updates. Not typically observed by host applications.
  ChatStateConfig = 11,
/// Internal state indicating the end queue was processed.
  ChatStateEndQueue = 12,
  ChatStateTyping = 13,
  ChatStateEndTyping = 14,
/// The chat deployment is unavailable (e.g., outside business hours or disabled).
  ChatStateUnavailable = 15,
/// The agent is currently typing a response.
  ChatStateAgentTyping = 16,
};

/// An event object representing a change in the chat session’s lifecycle state.
/// <code>ChatStateEvent</code> is delivered through <code>ChatControllerDelegate/didUpdateState(_:)</code>
/// each time the chat transitions between states. Use the <code>state</code> property to determine
/// the current lifecycle phase, and <code>dataMsg</code> for any associated payload.
/// <h2>Associated Data</h2>
/// For <code>.chatEnded</code> and <code>.chatClosed</code> states, <code>dataMsg</code> contains the raw <code>Int</code> value of an
/// <code>EndedReason</code> enum case, indicating why the chat ended:
/// \code
/// if event.state == .chatClosed,
///    let reasonValue = event.dataMsg as? Int,
///    let reason = EndedReason(rawValue: reasonValue) {
///     switch reason {
///     case .sessionExpired:
///         showSessionExpiredMessage()
///     case .conversationCleared:
///         showConversationClearedMessage()
///     default:
///         dismissChatUI()
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC16GenesysCloudCore14ChatStateEvent")
@interface ChatStateEvent : NSObject
/// The current state of the chat session.
@property (nonatomic) enum ChatState state;
/// Optional data associated with the state transition.
/// For <code>.chatEnded</code> and <code>.chatClosed</code> states, this contains the <code>EndedReason</code> raw value as an <code>Int</code>.
/// For other states, this is typically <code>nil</code>.
@property (nonatomic) id _Nullable dataMsg;
- (nonnull instancetype)initWithState:(enum ChatState)state dataMsg:(id _Nullable)dataMsg OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)initWithState:(enum ChatState)state OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC16GenesysCloudCore24DefaultConnectionHandler") SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.")
@interface DefaultConnectionHandler : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSession;
@class NSURLSessionTask;
@interface DefaultConnectionHandler (SWIFT_EXTENSION(GenesysCloudCore)) <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
@end

/// Represents a downloadable file attachment within a <code>FileChatElement</code>.
/// This class holds the metadata and binary data for files exchanged in the conversation.
/// Consumer applications can read <code>fileName</code>, <code>fileData</code>, and <code>fileSizeInBytes</code> to access
/// the file’s content.
SWIFT_CLASS("_TtC16GenesysCloudCore16DownloadableFile")
@interface DownloadableFile : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The reason a chat session ended.
/// This value is delivered as the <code>ChatStateEvent/dataMsg</code> payload (as a raw <code>Int</code>) when the
/// chat transitions to <code>.chatEnded</code> or <code>.chatClosed</code> states.
typedef SWIFT_ENUM(NSInteger, EndedReason, open) {
/// The chat ended for an unknown or unexpected reason.
  EndedReasonUnknown = 0,
/// The chat was ended by an agent or operator.
  EndedReasonOperator = 1,
/// The chat was ended by the user (visitor) while the session was still active.
  EndedReasonVisitor = 2,
/// The chat was disconnected.
  EndedReasonDisconnected = 3,
/// The chat was terminated by the hosting application.
  EndedReasonApp = 4,
/// The connection was closed because the maximum number of simultaneous open sessions was exceeded.
  EndedReasonSessionLimitReached = 5,
/// The connection was closed as a result of calling <code>ChatController/clearConversation()</code>.
  EndedReasonConversationCleared = 6,
/// The connection was closed following a successful logout from an authenticated session.
  EndedReasonLogout = 7,
/// The session ended due to inactivity timeout.
  EndedReasonSessionExpired = 8,
};

/// A chat element representing a file attachment (image, document, video, etc.).
/// <code>FileChatElement</code> is delivered when a file is sent or received in the conversation.
/// Access the file metadata and data through the <code>file</code> property.
/// <h2>Accessing File Information</h2>
/// \code
/// if let fileElement = chatElement as? FileChatElement {
///     if let data = fileElement.file.fileData {
///         // Use the file data
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC16GenesysCloudCore15FileChatElement")
@interface FileChatElement : ChatElement
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind file:(DownloadableFile * _Nonnull)file text:(NSString * _Nullable)text OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind SWIFT_UNAVAILABLE;
@end

/// An error object delivered through <code>ChatControllerDelegate/didFailWithError(_:)</code>.
/// <code>GCError</code> wraps a <code>ChatError</code> code with an optional human-readable description. Use
/// <code>errorType</code> to programmatically determine the failure category, and <code>errorDescription</code>
/// to display a message to the user.
SWIFT_CLASS("_TtC16GenesysCloudCore7GCError")
@interface GCError : NSObject
@property (nonatomic) NSError * _Nullable error SWIFT_DEPRECATED_MSG("Will be removed in 3.0.0. GCError conforms to Error directly.");
/// The category of the error. Use this to determine the appropriate recovery action.
@property (nonatomic) enum ChatError errorType;
/// A human-readable description of the error, suitable for display to the user.
@property (nonatomic, copy) NSString * _Nullable errorDescription;
- (nonnull instancetype)initWithError:(NSError * _Nullable)error errorType:(enum ChatError)errorType errorDescription:(NSString * _Nullable)errorDescription OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Use init(errorType:errorDescription:) instead. Will be removed in 3.0.0.");
/// Creates a new error with the specified type and optional description.
/// \param errorType The <code>ChatError</code> code identifying the failure category.
///
/// \param errorDescription An optional human-readable message describing the error.
///
- (nonnull instancetype)initWithErrorType:(enum ChatError)errorType errorDescription:(NSString * _Nullable)errorDescription OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC16GenesysCloudCore15LanguageUtility") SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.")
@interface LanguageUtility : NSObject
- (NSString * _Nullable)getDeviceLanguage SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// A chat element representing a set of quick reply buttons suggested by the bot or agent.
/// Quick replies are short, tappable response options presented to the user.
/// <h2>Displaying Quick Replies</h2>
/// \code
/// if let quickReplies = chatElement as? QuickRepliesChatElement {
///     for reply in quickReplies.quickReplies {
///         // Handle options
///     }
/// }
///
/// \endcode
SWIFT_CLASS("_TtC16GenesysCloudCore23QuickRepliesChatElement")
@interface QuickRepliesChatElement : ChatElement
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp quickReplies:(NSArray<NSString *> * _Nonnull)quickReplies OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC16GenesysCloudCore19RemoteConfiguration") SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.")
@interface RemoteConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum SystemChatElementType : NSInteger;
/// A chat element representing a system-generated event in the conversation.
/// System elements indicate lifecycle transitions such as conversation start, end, resume,
/// or disconnect. They are typically non-interactive messages.
SWIFT_CLASS("_TtC16GenesysCloudCore17SystemChatElement")
@interface SystemChatElement : ChatElement
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp type:(enum SystemChatElementType)type text:(NSString * _Nullable)text OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind SWIFT_UNAVAILABLE;
@end

/// The type of system event represented by a <code>SystemChatElement</code>.
typedef SWIFT_ENUM(NSInteger, SystemChatElementType, open) {
/// The conversation was auto-started by the deployment configuration.
  SystemChatElementTypeAutoStart = 0,
/// A new conversation has been initiated.
  SystemChatElementTypeNewConversation = 1,
/// The user explicitly started a conversation.
  SystemChatElementTypeStartConversation = 2,
/// The conversation has been successfully started and is active.
  SystemChatElementTypeConversationStarted = 3,
/// The conversation has ended.
  SystemChatElementTypeConversationEnded = 4,
/// A previously disconnected conversation has been resumed.
  SystemChatElementTypeConversationResumed = 5,
/// The conversation was disconnected by the agent.
  SystemChatElementTypeConversationDisconnect = 6,
};

/// A chat element representing a plain text message.
/// <code>TextChatElement</code> is the most common element type, representing messages sent by the user,
/// agent, or bot. Check the inherited <code>ChatElement/kind</code> property to determine the sender.
SWIFT_CLASS("_TtC16GenesysCloudCore15TextChatElement")
@interface TextChatElement : ChatElement
/// The text content of the message. May contain HTML markup for rich formatting.
@property (nonatomic, copy) NSString * _Nonnull text;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind text:(NSString * _Nonnull)text OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind SWIFT_UNAVAILABLE;
@end

/// A single available time slot within a <code>TimeSlotPickerChatElement</code>.
/// Each <code>TimeSlot</code> represents one bookable date/time option presented to the user.
SWIFT_CLASS("_TtC16GenesysCloudCore8TimeSlot")
@interface TimeSlot : NSObject
/// The date and time of this available slot.
@property (nonatomic, readonly, copy) NSDate * _Nonnull dateTime;
/// The postback payload sent to the bot when this time slot is selected.
@property (nonatomic, readonly, copy) NSString * _Nonnull payload;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A chat element confirming the user’s selected time slot.
/// This element is displayed after the user selects a time from a <code>TimeSlotPickerChatElement</code>,
/// serving as a visual confirmation of their booking choice.
SWIFT_CLASS("_TtC16GenesysCloudCore31TimeSlotConfirmationChatElement")
@interface TimeSlotConfirmationChatElement : ChatElement
/// The confirmation text displayed to the user.
@property (nonatomic, copy) NSString * _Nonnull text;
/// The postback payload identifying the selected time slot.
@property (nonatomic, readonly, copy) NSString * _Nonnull payload;
/// The ID of the originating picker message, or <code>nil</code> if unavailable.
@property (nonatomic, readonly, copy) NSString * _Nullable originatingMessageId;
/// The URL of an optional confirmation image, or <code>nil</code> if none is provided.
@property (nonatomic, copy) NSString * _Nullable imageUrl;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind SWIFT_UNAVAILABLE;
@end

/// A chat element presenting available time slots for the user to select from.
/// This element is sent by a bot when scheduling functionality is configured. It displays
/// a list of available date/time options that the user can choose from to book an appointment.
SWIFT_CLASS("_TtC16GenesysCloudCore25TimeSlotPickerChatElement")
@interface TimeSlotPickerChatElement : ChatElement
/// The title displayed above the time slot picker.
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
/// An optional subtitle providing additional context about the scheduling options.
@property (nonatomic, readonly, copy) NSString * _Nullable subtitle;
/// The URL of an optional header image for the picker, or <code>nil</code> if none is provided.
@property (nonatomic, readonly, copy) NSString * _Nullable imageUrl;
/// The list of available time slots the user can select from.
@property (nonatomic, readonly, copy) NSArray<TimeSlot *> * _Nonnull availableTimes;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind SWIFT_UNAVAILABLE;
@end

/// A chat element indicating that the agent is currently typing.
/// This element is delivered when the agent begins typing and is typically used to display
/// a typing animation in the chat UI. It is transient and will not persist in conversation history.
/// note:
/// The <code>ChatElement/kind</code> for this element is always <code>.agent</code>.
SWIFT_CLASS("_TtC16GenesysCloudCore26TypingIndicatorChatElement")
@interface TypingIndicatorChatElement : ChatElement
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Not for external use. Public access will be removed in 3.0.0.");
+ (nonnull instancetype)new;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id isLoadedFromHistory:(BOOL)isLoadedFromHistory timestamp:(NSDate * _Nonnull)timestamp kind:(enum ChatElementKind)kind SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, UnavailableReason, open) {
  UnavailableReasonQueueFull = 0,
  UnavailableReasonNoOperators = 1,
  UnavailableReasonVisitorBlocked = 2,
  UnavailableReasonOutsideHours = 3,
  UnavailableReasonUnknown = 4,
  UnavailableReasonAnswerTimeout = 5,
  UnavailableReasonUnsecure = 6,
  UnavailableReasonError = 7,
  UnavailableReasonNoConnection = 8,
  UnavailableReasonServiceUnavailable = 9,
  UnavailableReasonServiceDisabled = 10,
  UnavailableReasonNoReason = 11,
};

/// Represents the delivery state of a user-sent chat element.
/// Observe changes to <code>ChatElement/userState</code> to update UI indicators (e.g., pending spinner,
/// error badge) for messages sent by the user.
typedef SWIFT_ENUM(NSInteger, UserChatElementState, open) {
/// No state has been assigned yet.
  UserChatElementStateNone = 0,
/// The element has been queued for sending but not yet transmitted.
  UserChatElementStatePending = 1,
/// The element was sent to the server but no response was received yet.
  UserChatElementStateInProcess = 2,
/// The element was successfully delivered.
  UserChatElementStateSuccess = 3,
/// The element failed to send.
  UserChatElementStateError = 4,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
